Linear Regression from Scratch using Pytorch

In [ ]:
import torch 
import numpy as np

In [ ]:
inputs_np = np.array([[122, 267, 143], 
                   [191, 88, 64], 
                   [287, 134, 158], 
                   [102, 243, 37], 
                   [659, 96, 70]], dtype='float32')

targets_np = np.array([[256, 710], 
                    [81, 101], 
                    [119, 133], 
                    [222, 137], 
                    [103, 119]], dtype='float32')

In [ ]:
inputs = torch.from_numpy(inputs_np)
targets = torch.from_numpy(targets_np)

In [ ]:
'''Initializing weights and biases
o/p_1 = w1 x para1 + w2 x para2 + w3 x para3 + b1(bias) 
o/p_2 = w4 x para1 + w5 x para2 + w6 x para3 + b2(bias)'''

w = torch.randn(2, 3, requires_grad = True) # 2 output targets, 3 input parameters, hence size is 2x3. 
b = torch.randn(2, requires_grad = True)


In [ ]:
### Defining the model
def model(x):
  return x @ w.t() + b ############ y = x.w_transpose + b, in pytorch dot product is given by @ while the transpose is given by .t()

predictions = model(inputs)


### Defining loss function
#### Mean Square Error loss, MSE = summation of (y_pred - y_true)^2/(n), where n is the number of elements in y_pred or y_true 
def loss_fn(t1, t2):
  diff = t1 - t2
  return torch.sum(diff*diff)/diff.numel()

mse_loss = loss_fn(predictions, targets)
print(targets)
print(predictions)
print(mse_loss)


tensor([[256., 710.],
        [ 81., 101.],
        [119., 133.],
        [222., 137.],
        [103., 119.]])
tensor([[ 137.3056,   86.4574],
        [ 102.1952, -115.6207],
        [ 180.4597, -220.4606],
        [  82.0060,  160.4643],
        [ 260.7285, -515.2204]], grad_fn=<AddBackward0>)
tensor(102624.1875, grad_fn=<DivBackward0>)


In [ ]:
### Perform gradient descent for 100 epochs

num_epochs = 10000
for i in range(num_epochs):
  preds = model(inputs)
  loss = loss_fn(preds, targets)
  loss.backward()
  
  with torch.no_grad(): # using torch.no_grad() to make sure that arithmetic operations below don't have impact on gardient
    w-=w.grad*1e-5 # Learning rate of 1e-5
    b-=b.grad*1e-5 
    w.grad.zero_() # Zeroing the gradients so that their is no addition of previous gradients to the current gradient value
    b.grad.zero_()


In [ ]:
### Check the loss on the trained model

preds_test = model(inputs)
loss = loss_fn(preds_test, targets)
print(loss)
print("We can see that loss has been reduced. It can be reduced further by hyperparameter tuning, using better optimization techniques and loss functions")

tensor(11890.3477, grad_fn=<DivBackward0>)
We can see that loss has been reduced. It can be reduced further by hyperparameter tuning, using better optimization techniques and loss functions


Linear Regression using Pytorch built-in functions

In [ ]:
import torch.nn as nn

In [ ]:
# Defining inputs and targets

inputs_np = np.array([[256, 710], 
                    [81, 101], 
                    [119, 133], 
                    [222, 137],
                    [352, 437], 
                    [103, 119]], dtype='float32')

targets_np = np.array([[256, 710], 
                    [81, 101], 
                    [119, 133], 
                    [222, 137],
                    [245, 145], 
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs_np)
targets = torch.from_numpy(targets_np)

In [ ]:
''' Importing Two modules from torch.utils.data namely, TensorDataset and DataLoader
    The TensorDataset function takes-in inputs and targets and gives them as a tuple 
    The DataLoader function is used for shuffling of the data and sorting the data into different batches(used when large data is there)
'''
from torch.utils.data import TensorDataset 
from torch.utils.data import DataLoader

## Defining the dataset as a tuple

train_ds =  TensorDataset(inputs, targets)

batch_size = 2
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

# Visualize the first batch of the dataset
for x, y in train_dl:
  print(x)
  print(y)
  break

tensor([[352., 437.],
        [119., 133.]])
tensor([[245., 145.],
        [119., 133.]])


In [ ]:
############### Define THE MODEL ##################

model1 = nn.Linear(3,2)
print(model.weight.shape)
print(model.bias)
print(list(model.parameters())) #### model.parameters contains all the parameter matrices(weights and biases) in the network (there can be more than one).


torch.Size([2, 3])
Parameter containing:
tensor([0.2681, 0.1994], requires_grad=True)
[Parameter containing:
tensor([[-0.5609,  0.3026,  0.4198],
        [-0.1237, -0.3806,  0.4897]], requires_grad=True), Parameter containing:
tensor([0.2681, 0.1994], requires_grad=True)]


In [ ]:
preds = model1(inputs)
preds

In [ ]:
#### Defining loss function

import torch.nn.functional as F

mse_loss = F.mse_loss


#### Define Optimizer

import torch.optim as optim

opt = optim.SGD(model.parameters(), lr = 1e-5)



In [ ]:
## Train the model
def fit(num_epochs,model, mse_loss, opt, train_dl):
  for epoch in range(num_epochs):
    for xb, yb in train_dl:
      pred = model(xb)
      loss = mse_loss(pred, yb)
      loss.backward()
      
      opt.step()
      opt.zero_grad()


In [ ]:
### Call the training function
fit(100, model, mse_loss, opt, train_dl)

### Test the trained model
predictions = model(inputs)
